#!/bin/bash
#!/bin/bash
### BEGIN INIT INFO
# Provides:          freeswitch
# Required-Start:    $local_fs $remote_fs
# Required-Stop:     $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       Freeswitch debian init script.
# Author:            Matthew Williams
#
### END INIT INFO
#docker run -v /home/ec2-user/data/:/jbrowse -p 80:80 erasche/jbrowse &
docker run -d -p 443:443 -v /home/ec2-user/etc/nginx:/etc/nginx:ro -v /home/ec2-user/data/:/jbrowse -v /home/ec2-user/ssl:/home/ec2-user/ssl -v /var/run/docker.sock:/tmp/docker.sock:ro erasche/jbrowse &
